### ISSUE TITLE
How to grant Network access

### ISSUE THREAD

**Issue by hand-dot** [moyukapp/moyuk#18]
Hey, What a cool app! I like moyuk. thank you.
I have a question.

> The users must explicitly grant the permissions to the apps. This feature imitates [Deno's allow-net permissions](https://deno.land/manual/basics/permissions#network-access).

How to grant Network access?

---

Ref: https://docs.moyukapp.com/apps/runtime#permissions

**Comment by kohii** [comment]
Hello! I'm glad to hear that you're enjoying Moyuk. Thank you for your kind words!

To answer your question about granting network access:

In Moyuk, it is the user, not the app creator, who grants network access permissions.

App creators simply write code using standard methods like fetch.

When a user runs the app for the first time, they will encounter a "PermissionDenied" error screen. Below this message, a button to allow network access will be displayed. By clicking this button, the user can grant network access permissions to the app.


![b71e475f3a24-20230403](https://user-images.githubusercontent.com/6891780/231500162-c8b5ded9-3ff5-4891-969d-bfe589f36a7a.png)

I am also planning to implement a feature for managing network access permissions, so please stay tuned for that!

I hope this helps! If you have any further questions or need clarification, feel free to ask.
